//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 03:52:44 PM CST 
//


package com.hollyvoc.data.pretreat.pares.voice.bean.thinkit;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hollycrm.textminer.util.thinkit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hollycrm.textminer.util.thinkit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link OkList }
     * 
     */
    public OkList createOkList() {
        return new OkList();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link InterruptionList }
     * 
     */
    public InterruptionList createInterruptionList() {
        return new InterruptionList();
    }

    /**
     * Create an instance of {@link Inter }
     * 
     */
    public Inter createInter() {
        return new Inter();
    }

    /**
     * Create an instance of {@link SilenceList }
     * 
     */
    public SilenceList createSilenceList() {
        return new SilenceList();
    }

    /**
     * Create an instance of {@link Silence }
     * 
     */
    public Silence createSilence() {
        return new Silence();
    }

    /**
     * Create an instance of {@link SentenceList }
     * 
     */
    public SentenceList createSentenceList() {
        return new SentenceList();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link WordList }
     * 
     */
    public WordList createWordList() {
        return new WordList();
    }

    /**
     * Create an instance of {@link Word }
     * 
     */
    public Word createWord() {
        return new Word();
    }

    /**
     * Create an instance of {@link KeywordList }
     * 
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

}
