//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 03:52:44 PM CST 
//


package com.hollyvoc.data.pretreat.pares.voice.bean.thinkit;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}interruption_list"/>
 *         &lt;element ref="{}silence_list"/>
 *         &lt;element ref="{}sentence_list"/>
 *         &lt;element ref="{}keyword_list"/>
 *       &lt;/sequence>
 *       &lt;attribute name="durtime" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="record_key" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interruptionList",
    "silenceList",
    "sentenceList",
    "keywordList"
})
@XmlRootElement(name = "record")
public class Record {

    @XmlElement(name = "interruption_list", required = true)
    protected InterruptionList interruptionList;
    @XmlElement(name = "silence_list", required = true)
    protected SilenceList silenceList;
    @XmlElement(name = "sentence_list", required = true)
    protected SentenceList sentenceList;
    @XmlElement(name = "keyword_list", required = true)
    protected KeywordList keywordList;
    @XmlAttribute(name = "durtime", required = true)
    protected BigInteger durtime;
    @XmlAttribute(name = "record_key", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String recordKey;

    /**
     * Gets the value of the interruptionList property.
     * 
     * @return
     *     possible object is
     *     {@link InterruptionList }
     *     
     */
    public InterruptionList getInterruptionList() {
        return interruptionList;
    }

    /**
     * Sets the value of the interruptionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterruptionList }
     *     
     */
    public void setInterruptionList(InterruptionList value) {
        this.interruptionList = value;
    }

    /**
     * Gets the value of the silenceList property.
     * 
     * @return
     *     possible object is
     *     {@link SilenceList }
     *     
     */
    public SilenceList getSilenceList() {
        return silenceList;
    }

    /**
     * Sets the value of the silenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SilenceList }
     *     
     */
    public void setSilenceList(SilenceList value) {
        this.silenceList = value;
    }

    /**
     * Gets the value of the sentenceList property.
     * 
     * @return
     *     possible object is
     *     {@link SentenceList }
     *     
     */
    public SentenceList getSentenceList() {
        return sentenceList;
    }

    /**
     * Sets the value of the sentenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SentenceList }
     *     
     */
    public void setSentenceList(SentenceList value) {
        this.sentenceList = value;
    }

    /**
     * Gets the value of the keywordList property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordList }
     *     
     */
    public KeywordList getKeywordList() {
        return keywordList;
    }

    /**
     * Sets the value of the keywordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordList }
     *     
     */
    public void setKeywordList(KeywordList value) {
        this.keywordList = value;
    }

    /**
     * Gets the value of the durtime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDurtime() {
        return durtime;
    }

    /**
     * Sets the value of the durtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDurtime(BigInteger value) {
        this.durtime = value;
    }

    /**
     * Gets the value of the recordKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordKey() {
        return recordKey;
    }

    /**
     * Sets the value of the recordKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordKey(String value) {
        this.recordKey = value;
    }

}
