//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 03:52:44 PM CST 
//


package com.hollyvoc.data.pretreat.pares.voice.bean.thinkit;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}word_list"/>
 *       &lt;/sequence>
 *       &lt;attribute name="emotion-score" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="emotion_type" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="end_time" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="speed" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="start_time" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wordList"
})
@XmlRootElement(name = "sentence")
public class Sentence {

    @XmlElement(name = "word_list", required = true)
    protected WordList wordList;
    @XmlAttribute(name = "emotion-score")
    @XmlSchemaType(name = "anySimpleType")
    protected String emotionScore;
    @XmlAttribute(name = "emotion_type", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String emotionType;
    @XmlAttribute(name = "end_time", required = true)
    protected BigInteger endTime;
    @XmlAttribute(name = "role", required = true)
    protected BigInteger role;
    @XmlAttribute(name = "speed", required = true)
    protected BigDecimal speed;
    @XmlAttribute(name = "start_time", required = true)
    protected BigInteger startTime;
    @XmlAttribute(name = "text", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String text;

    /**
     * Gets the value of the wordList property.
     * 
     * @return
     *     possible object is
     *     {@link WordList }
     *     
     */
    public WordList getWordList() {
        return wordList;
    }

    /**
     * Sets the value of the wordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordList }
     *     
     */
    public void setWordList(WordList value) {
        this.wordList = value;
    }

    /**
     * Gets the value of the emotionScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmotionScore() {
        return emotionScore;
    }

    /**
     * Sets the value of the emotionScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmotionScore(String value) {
        this.emotionScore = value;
    }

    /**
     * Gets the value of the emotionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmotionType() {
        return emotionType;
    }

    /**
     * Sets the value of the emotionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmotionType(String value) {
        this.emotionType = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndTime(BigInteger value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRole(BigInteger value) {
        this.role = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeed(BigDecimal value) {
        this.speed = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartTime(BigInteger value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
