//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 02:34:50 下午 CST 
//


package com.hollyvoc.data.pretreat.pares.voice.bean.sinovoice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hollycrm.textminer.util.voice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _Duration_QNAME = new QName("", "duration");
    private final static QName _KeywordList_QNAME = new QName("", "keyword_list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hollycrm.textminer.util.voice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Emotion }
     * 
     */
    public Emotion createEmotion() {
        return new Emotion();
    }

    /**
     * Create an instance of {@link Word }
     * 
     */
    public Word createWord() {
        return new Word();
    }

    /**
     * Create an instance of {@link WordList }
     * 
     */
    public WordList createWordList() {
        return new WordList();
    }

    /**
     * Create an instance of {@link SentenceList }
     * 
     */
    public SentenceList createSentenceList() {
        return new SentenceList();
    }

    /**
     * Create an instance of {@link Silence }
     * 
     */
    public Silence createSilence() {
        return new Silence();
    }

    /**
     * Create an instance of {@link EmotionList }
     * 
     */
    public EmotionList createEmotionList() {
        return new EmotionList();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link SilenceList }
     * 
     */
    public SilenceList createSilenceList() {
        return new SilenceList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "duration")
    public JAXBElement<BigInteger> createDuration(BigInteger value) {
        return new JAXBElement<BigInteger>(_Duration_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keyword_list")
    public JAXBElement<String> createKeywordList(String value) {
        return new JAXBElement<String>(_KeywordList_QNAME, String.class, null, value);
    }

}
